src/AppBundle/Entity/Transaction.php
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TransactionRepository")
 * @ORM\Table(name="transaction")
 */
class Transaction
{
    const STATUS_PENDING = 0;
    const STATUS_APPROVED = 1;
    const STATUS_REFUNDED = 2;

    public static $statuses = [
        'labels.pending' => self::STATUS_PENDING,
        'labels.approved' => self::STATUS_APPROVED,
        'labels.refunded' => self::STATUS_REFUNDED,
    ];

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=2)
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=55)
     */
    private $vendorId;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status = self::STATUS_PENDING;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="transactions")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Order", mappedBy="transaction")
     */
    private $order;

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param float $amount
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    }

    /**
     * @return string
     */
    public function getVendorId()
    {
        return $this->vendorId;
    }

    /**
     * @param string $vendorId
     */
    public function setVendorId($vendorId)
    {
        $this->vendorId = $vendorId;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return Order
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * @param Order $order
     */
    public function setOrder($order)
    {
        $this->order = $order;
    }

    /**
     * @return string|null
     */
    public function getStatusName()
    {
        if (in_array($this->status, self::$statuses, true)) {
            return array_search($this->status, self::$statuses);
        }

        return null;
    }
}

src/AppBundle/Controller/Admin/TransactionController.php
<?php
namespace AppBundle\Controller\Admin;

use AppBundle\Entity\Transaction;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/transaction")
 * Class AdminTransactionController
 * @package AppBundle\Controller
 */
class TransactionController extends Controller
{
    /**
     * @Route("/", name="admin_transaction_index")
     * @param Request $request
     * @return Response
     */
    public function indexAction(Request $request)
    {
        $page = $request->query->get('page', 1);
        $transactions = $this->get('app.transaction_manager')->getFindAllPaginator($page);

        return $this->render('AppBundle:Admin/Transaction:index.html.twig', [
            'transactions' => $transactions,
            'total' => $transactions->getTotalItemCount(),
        ]);
    }

    /**
     * @Route("/refund/{transaction}", name="admin_transaction_refund")
     * @param Transaction $transaction
     * @return Response
     */
    public function refundAction(Transaction $transaction)
    {
        if ($transaction->getStatus() !== Transaction::STATUS_APPROVED) {
            throw $this->createNotFoundException();
        }

        // TODO refund

        return $this->redirectToRoute('admin_transaction_index');
    }
}

src/AppBundle/Resources/views/Admin/Transaction/index.html.twig
{% extends "@App/Admin/layout.html.twig" %}
{% block content %}
    <h2>{{ 'labels.transactions'|trans }}</h2>

    <table class="table  table-striped">
        <thead>
            <tr>
                <th>{{ 'labels.id'|trans }}</th>
                <th>{{ 'labels.title'|trans }}</th>
                <th>{{ 'labels.vendor_id'|trans }}</th>
                <th>{{ 'labels.status'|trans }}</th>
                <th>{{ 'labels.user'|trans }}</th>
                <th class="text-center" width="125">{{ 'labels.actions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>${{ transaction.amount }}</td>
                    <td>${{ transaction.vendorId }}</td>
                    <td>{{ transaction.statusName|trans }}</td>
                    <td>
                        <a href="{{ path('admin_user_edit', {'user' : transaction.user.id }) }}">{{ transaction.user.email }}</a>
                    </td>
                    <td class="text-center">
                        {% if transaction.status == 1 %}
                            <a class="btn btn-danger btn-sm confirm" href="{{ path('admin_transaction_refund', {'transaction': transaction.id}) }}">
                                {{ 'verb.refund'|trans }}
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-md-12 media-middle"><p><strong>{{ 'labels.total_results'| trans }}:</strong> {{ total }}</p></div>
    <div class="col-md-12 text-center pagination">{{ knp_pagination_render(transactions) }}</div>
    <div class="clearfix"></div>
{% endblock %}